### ISSUE TITLE
Setup  Ansible Inventory Variables

### ISSUE THREAD

**Issue by Cdaprod** [Cdaprod/BugBounty-Infrastructure#1]
You can define variables in your Ansible inventory file. This can be done in a couple of ways, but one common approach is to group your hosts and define variables for that group. Here's an example of how you might structure your inventory file:

```ini
[workstations]
attack.cdaworkstation.com
database.cdaworkstation.com
proxy.cdaworkstation.com

[workstations:vars]
ansible_user=your_username
ansible_ssh_private_key_file=/path/to/your/private/key
```

In the example above, the `ansible_user` and `ansible_ssh_private_key_file` variables are defined for the `workstations` group, which includes `attack.cdaworkstation.com`, `database.cdaworkstation.com`, and `proxy.cdaworkstation.com`.

You can then use these variables in your Ansible playbooks. For example, you could modify the Certbot playbook I provided earlier to use the hosts and variables from your inventory file:

```yaml
- hosts: workstations
  tasks:
    - name: Install Certbot and the NGINX plugin
      apt:
        name: 
          - certbot 
          - python3-certbot-nginx 
        state: present

    - name: Obtain a certificate
      command: certbot --nginx -d {{ inventory_hostname }} -m admin@{{ inventory_hostname }} --agree-tos --no-eff-email --redirect
      args:
        creates: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
```

In this playbook, `{{ inventory_hostname }}` is a built-in Ansible variable that represents the hostname of the current host. It's replaced with the actual hostname when the playbook is run. 

This playbook will run the Certbot command for each host in the `workstations` group, using the hostname for the `-d` (domain) and `-m` (email) options. The `creates` argument is also updated to check for the certificate in the directory specific to each hostname.

Please note that this playbook assumes that each host is running NGINX and that you want to obtain a separate certificate for each host. If this is not the case, you'll need to adjust the playbook accordingly.

Remember to replace `your_username` and `/path/to/your/private/key` with your actual username and the path to your SSH private key. You'll also need to replace `admin@{{ inventory_hostname }}` with the actual email address you want to use for Let's Encrypt.
