### ISSUE TITLE
Enhance Ansible Common Role for Infrastructure Setup

### ISSUE THREAD

**Issue by Cdaprod** [Cdaprod/BugBounty-Infrastructure#10]
**Issue:**

We need to enhance our Ansible common role to include more advanced setup configurations. This role is critical for setting up our server infrastructure with common tasks such as updating packages, installing essential tools, configuring security, managing users, and setting up any other common configurations.

**Instructions:**

1. If not already done, create a new directory inside the roles directory called `common`.

2. Create or update the `main.yml` file inside the `tasks` directory with the following tasks:

   ```yaml
   ---
   # tasks file for common
   - name: Update all packages
     apt: 
       update_cache: yes
       upgrade: yes

   - name: Install necessary packages
     apt: 
       name: "{{ item }}"
       state: present
     loop: "{{ packages }}"
   
   - name: Create user
     user:
       name: "{{ username }}"
       state: present
       createhome: yes
       password: "{{ password }}"
       shell: /bin/bash
     become: yes

   - name: Add user to sudoers
     copy:
       dest: /etc/sudoers.d/{{ username }}
       content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
       validate: 'visudo -cf %s'
     become: yes
   ```

3. Update the `vars/main.yml` file to include the necessary packages and user details:

   ```yaml
   ---
   # vars file for common
   packages:
     - curl
     - vim
     - htop
     - git
   username: your_user
   password: "{{ 'your_password' | password_hash('sha512') }}"
   ```

4. If you need to copy files or use templates, place them in the `files` or `templates` directory respectively.

5. If you need to handle service restarts or other notifications, add them to `handlers/main.yml`.

6. In the `meta/main.yml` file, define the role dependencies if any.

7. Update your playbook to include this role for your hosts. 

   ```yaml
   ---
   - hosts: all
     become: yes
     roles:
       - common
   ```

**Acceptance Criteria:**

1. The common role is enhanced with the necessary tasks and configurations.

2. The role is idempotent, meaning it can be run multiple times without changing the result beyond the initial application.

3. The role installs and updates all necessary packages on the servers.

4. The role correctly creates the user with the specified username and password, and adds them to the sudoers file.

5. The playbook runs successfully and all tasks in the common role are completed without errors.

---

Please replace `your_user` and `your_password` with your actual username and password. Remember that storing passwords in plain text is not secure. Use Ansible Vault or another secure method for managing your secrets. 

Also note that this issue assumes that you are using a Debian-based system due to the use of the `apt` module. If you're using a different system like CentOS or RedHat, you'll need to use the `yum` module instead.
