### ISSUE TITLE
Ansible will configure SSL certificates per host by subdomain or setting wildcard subdomain.

### ISSUE THREAD

**Issue by Cdaprod** [Cdaprod/BugBounty-Infrastructure#2]
Let's Encrypt is a free, automated, and open Certificate Authority (CA) that provides TLS (HTTPS) certificates. Certbot is a fully-featured, extensible client for Let's Encrypt CA that can automate certificate tasks on your server. 

To ensure that your reconnaissance scans, database, and proxy are trusted, you would need to set up Certbot on your server to issue and renew certificates automatically. Below is an example of how you might use Ansible to set up Certbot for an NGINX server:

```yaml
- name: Install Certbot and the NGINX plugin
  apt:
    name: 
      - certbot 
      - python3-certbot-nginx 
    state: present

- name: Obtain a certificate
  command: certbot --nginx -d example.com -d www.example.com -m admin@example.com --agree-tos --no-eff-email --redirect
  args:
    creates: /etc/letsencrypt/live/example.com/fullchain.pem
```

This will install Certbot and its NGINX plugin, then obtain a certificate for `example.com` and `www.example.com`, with the contact email `admin@example.com`. The `--agree-tos` and `--no-eff-email` options automatically agree to the Let's Encrypt terms of service and prevent Certbot from sending you email.

The command also includes the `--redirect` option, which tells Certbot to set up a redirection from HTTP to HTTPS. If your NGINX configuration file for the domain is located at a non-standard location, you can point Certbot to it with the `--nginx-server-root` option.

This certificate will need to be renewed every 90 days. You can set up a cron job or a systemd timer to run `certbot renew` twice a day, which will automatically renew any certificates that are within 30 days of expiration.

Remember to replace `example.com` and `www.example.com` with your actual domain names.

Please note that for Certbot to work, your server must be accessible from the internet and the domain names you're requesting certificates for must correctly resolve to the server. If you're setting up a database or a proxy server, you might need additional steps to ensure that these services use the certificates obtained by Certbot. 

As for your reconnaissance scans, whether they're trusted or not will depend on the tools you're using and how they handle HTTPS connections. Some tools might require you to configure them to trust the Let's Encrypt root certificate. Others might do this automatically. 

For databases, the process of setting up SSL/TLS can vary widely depending on the database system you're using. Some databases have built-in support for SSL/TLS, while others might require a proxy or a VPN to secure connections.
